Sidebar layout for worker page
DSSCKWA/car-rental-system pull request #14
Opened 2023-04-19 17:38 UTC by kjez21

2023-04-19 17:55 UTC, Goorsky1 requested changes

2023-04-19 17:55 UTC, Goorsky1 commented on frontend/vite.config.js.timestamp-1680621078544.mjs
> +import { defineConfig } from "file:///C:/Users/Karolina/WebstormProjects/ISI%20Car%20Rental%20System/car-rental-system/frontend/node_modules/vite/dist/node/index.js";
ten plik to raczej z gita trza wywalic

2023-04-20 14:04 UTC, Lukas4023 approved these changes

2023-04-20 19:32 UTC, kjez21 commented on frontend/vite.config.js.timestamp-1680621078544.mjs
> +import { defineConfig } from "file:///C:/Users/Karolina/WebstormProjects/ISI%20Car%20Rental%20System/car-rental-system/frontend/node_modules/vite/dist/node/index.js";
Done

2023-04-20 19:33 UTC, Goorsky1 approved these changes

2023-04-20 19:35 UTC, merged