add rentals display
DSSCKWA/car-rental-system pull request #24
Opened 2023-04-28 15:55 UTC by Lukas4023

2023-04-28 16:00 UTC, woj-mal09 approved these changes
Chyba tam przy insurance'ach czegoś może brakować, ale to jak ja wystawie kiedyś PR'a to sie zobaczy

2023-04-28 19:48 UTC, kjez21 requested changes

2023-04-28 19:48 UTC, kjez21 commented on backend/src/controllers/rentals.py
> +    if user_permissions == "manager" or user_permissions == "worker":
Można to przerobić na ```if user_permissions in ["manager", "worker"]```

2023-04-28 19:48 UTC, kjez21 commented on frontend/src/components/WorkerRentalsPage.jsx
> +                    navigate('');
Co to robi?

2023-04-28 19:48 UTC, kjez21 commented on frontend/src/components/WorkerRentalsPage.jsx
> +    // async function change_rental_status(id, account_status) {
Ten komentarz chyba zbędny

2023-04-28 19:48 UTC, kjez21 commented on frontend/src/components/WorkerRentalsPage.jsx
> +            {/*<Link to="/manager/add-rental">Add rental</Link>*/}
To zbędne

2023-04-28 19:48 UTC, kjez21 commented on frontend/src/components/WorkerRentalsPage.jsx
> +        <div className='manager_rentalsManagerRentalsPage.jsx_page'>
Co tu się stało?

2023-04-28 19:48 UTC, kjez21 commented on frontend/src/components/WorkerRentalsPage.jsx
> +                <th>Rental ID</th>
Do tych ```<th>``` najlepiej dodać wcięcia

2023-04-28 21:20 UTC, Goorsky1 submitted a review, later dismissed

2023-04-29 10:33 UTC, Lukas4023 commented on backend/src/controllers/users.py
> +@login_required
racja, @login_required wszędzie powinniśmy mieć bezpośrednio nad definicją funkcji

2023-04-29 10:34 UTC, Lukas4023 commented on frontend/src/components/WorkerRentalsPage.jsx
> +        <div className='manager_rentalsManagerRentalsPage.jsx_page'>
powinno być <div className='worker_rentals_page page_content'>, poprawiam

2023-04-29 10:36 UTC, Lukas4023 commented on frontend/src/components/WorkerRentalsPage.jsx
> +                <th>Rental ID</th>
Automatyczne formatowanie Pycharma usuwa je i przerabia na takie formatowanie, chyba nie ma sensu z nim się kłócić

2023-04-29 16:38 UTC, kjez21 approved these changes

2023-04-30 11:43 UTC, merged