CRS-46; Manager rental history + date filtering
DSSCKWA/car-rental-system pull request #39
Opened 2023-05-27 12:58 UTC by woj-mal09

2023-05-27 21:28 UTC, kjez21 requested changes

2023-05-27 21:28 UTC, kjez21 commented on frontend/src/components/pages/manager/ManagerPage.jsx
> +//import './ManagerStyles.css'
Ten komentarz do wywalenia

2023-05-27 21:28 UTC, kjez21 commented on frontend/src/components/pages/manager/ManagerPage.jsx
> +//import './ManagerStyles.css'
Plik z CSS'ami w sumie też do wywalenia teraz

2023-05-27 21:28 UTC, kjez21 commented on frontend/src/components/pages/manager/ManagerRentalsPage.jsx
> +            <form className='rental_time_search_from' onSubmit={e => {
Tutaj użyj naszego komponentu `<Form/>`

2023-05-27 21:47 UTC, Goorsky1 requested changes

2023-05-27 21:47 UTC, Goorsky1 commented on backend/src/controllers/vehicles.py
> +    vehicle = Rental.query.get(id)
to na pewno tak ma być?

2023-05-27 21:47 UTC, Goorsky1 commented on backend/src/controllers/vehicles.py
> +    new_vehicle = Rental(new_vehicle_body)
i tu i niżej

2023-05-27 21:47 UTC, Goorsky1 commented on backend/src/utils/validator.py
> +    vehicle = Rental.query.filter_by(registration_number=reg_number).first()
tu też coś się niedobrego podziało

2023-05-28 17:10 UTC, Goorsky1 approved these changes

2023-05-29 20:07 UTC, kjez21 approved these changes

2023-05-29 20:07 UTC, merged