Feat/register login backend
DSSCKWA/car-rental-system pull request #4
Opened 2023-04-03 08:05 UTC by Lukas4023

2023-04-03 18:39 UTC, Goorsky1 approved these changes

2023-04-03 21:13 UTC, kjez21 requested changes

2023-04-03 21:13 UTC, kjez21 commented on backend/src/controllers/auth.py
Brak endpointa do sprawdzania, czy użytkownik jest zalogowany (lub kim jest -> /me || /userinfo)

2023-04-03 21:13 UTC, kjez21 commented on backend/src/models/user.py
> +        # return {
Czy ten komentarz jest potrzebny?

2023-04-03 21:13 UTC, kjez21 commented on backend/src/controllers/auth.py
> +            return user.serialize()
Tutaj niepotrzebnie zwracamy hash hasła

2023-04-03 21:13 UTC, kjez21 commented on backend/src/controllers/auth.py
> +        return new_user.serialize()
Znowu niepotrzebnie zwracane hasło

2023-04-05 19:54 UTC, Goorsky1 commented on backend/src/controllers/auth.py
> +        return new_user.serialize()
poprawione

2023-04-05 19:54 UTC, Goorsky1 commented on backend/src/controllers/auth.py
> +            return user.serialize()
poprawione

2023-04-05 19:54 UTC, Goorsky1 commented on backend/src/controllers/auth.py
dodane

2023-04-05 19:55 UTC, Goorsky1 commented on backend/src/models/user.py
> +        # return {
usunięty

2023-04-06 09:55 UTC, kjez21 approved these changes

2023-04-06 09:57 UTC, merged