feat: add reset password feature
DSSCKWA/car-rental-system pull request #9
Opened 2023-04-16 13:46 UTC by Goorsky1

2023-04-16 13:49 UTC, woj-mal09 approved these changes
looks good to me, but i am kinda blind... soo...

2023-04-16 22:33 UTC, kjez21 requested changes

2023-04-16 22:33 UTC, kjez21 commented on backend/src/controllers/users.py
> +    validate_password_change(user,current_password,new_password, confirm_new_password)
Sformatuj kod plz

2023-04-16 22:33 UTC, kjez21 commented on backend/src/controllers/users.py
> +    user.password=bcrypt.generate_password_hash(new_password).decode("utf-8")
tu też

2023-04-16 22:47 UTC, Goorsky1 commented on backend/src/controllers/users.py
> +    validate_password_change(user,current_password,new_password, confirm_new_password)
k

2023-04-16 22:47 UTC, Goorsky1 commented on backend/src/controllers/users.py
> +    user.password=bcrypt.generate_password_hash(new_password).decode("utf-8")
k

2023-04-17 06:14 UTC, kjez21 approved these changes

2023-04-17 09:38 UTC, merged